-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 04_create_inventory_promotion_tables.sql
-- PURPOSE:
--   Tạo các bảng:
--   - Tồn kho theo chi nhánh
--   - Chương trình khuyến mãi
--   - Đối tượng áp dụng khuyến mãi
-- DATABASE: PostgreSQL / Supabase
-- =========================================================

BEGIN;

-- =========================================================
-- 0. CREATE SCHEMAS
-- =========================================================

CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS promotion;

-- =========================================================
-- 1. INVENTORY
-- =========================================================

CREATE TABLE IF NOT EXISTS inventory.inventory (
    inventory_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    branch_id INTEGER NOT NULL,

    variant_id INTEGER NOT NULL,

    quantity INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_inventory_branch
        FOREIGN KEY (branch_id)
        REFERENCES iam.branch(branch_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_inventory_variant
        FOREIGN KEY (variant_id)
        REFERENCES catalog.product_variant(variant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_inventory_branch_variant
        UNIQUE (
            branch_id,
            variant_id
        ),

    CONSTRAINT chk_inventory_quantity
        CHECK (quantity >= 0)
);

-- =========================================================
-- 2. PROMOTION
-- =========================================================

CREATE TABLE IF NOT EXISTS promotion.promotion (
    promotion_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    promotion_name VARCHAR(255) NOT NULL,

    discount_type VARCHAR(20) NOT NULL,

    discount_value NUMERIC(14,2) NOT NULL,

    max_discount_amount NUMERIC(14,2),

    min_order_value NUMERIC(14,2) NOT NULL DEFAULT 0,

    start_date DATE NOT NULL,

    end_date DATE NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_promotion_name
        UNIQUE (promotion_name),

    CONSTRAINT chk_promotion_discount_type
        CHECK (
            discount_type IN (
                'FIXED_AMOUNT',
                'PERCENTAGE'
            )
        ),

    CONSTRAINT chk_promotion_discount_value
        CHECK (
            discount_value > 0
        ),

    CONSTRAINT chk_promotion_percentage
        CHECK (
            discount_type <> 'PERCENTAGE'
            OR discount_value <= 100
        ),

    CONSTRAINT chk_promotion_max_discount
        CHECK (
            max_discount_amount IS NULL
            OR max_discount_amount >= 0
        ),

    CONSTRAINT chk_promotion_min_order_value
        CHECK (
            min_order_value >= 0
        ),

    CONSTRAINT chk_promotion_date_range
        CHECK (
            start_date <= end_date
        ),

    CONSTRAINT chk_promotion_status
        CHECK (
            status IN (
                'DRAFT',
                'SCHEDULED',
                'ACTIVE',
                'INACTIVE',
                'EXPIRED',
                'CANCELLED'
            )
        )
);

-- =========================================================
-- 3. PROMOTION_TARGET
-- =========================================================
-- Quy ước:
-- - COLLECTION: áp dụng cho một bộ sưu tập
-- - CATEGORY: áp dụng cho một danh mục
-- - PRODUCT_LINE: áp dụng cho một dòng sản phẩm
-- - Nếu khuyến mãi áp dụng toàn hệ thống thì không tạo
--   dòng nào trong bảng promotion_target cho promotion đó.
--
-- target_id là liên kết đa hình nên PostgreSQL không thể
-- tạo một FOREIGN KEY trực tiếp đến nhiều bảng khác nhau.
-- =========================================================

CREATE TABLE IF NOT EXISTS promotion.promotion_target (
    promotion_target_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    promotion_id INTEGER NOT NULL,

    target_type VARCHAR(30) NOT NULL,

    target_id INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_promotion_target_promotion
        FOREIGN KEY (promotion_id)
        REFERENCES promotion.promotion(promotion_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_promotion_target
        UNIQUE (
            promotion_id,
            target_type,
            target_id
        ),

    CONSTRAINT chk_promotion_target_type
        CHECK (
            target_type IN (
                'COLLECTION',
                'CATEGORY',
                'PRODUCT_LINE'
            )
        ),

    CONSTRAINT chk_promotion_target_id
        CHECK (
            target_id > 0
        )
);

COMMIT;