-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 06_create_return_review_tables.sql
-- PURPOSE:
--   Tạo các bảng:
--   - Yêu cầu đổi trả
--   - Chi tiết sản phẩm đổi trả
--   - Hoàn tiền
--   - Đánh giá sản phẩm
--   - Media đánh giá
-- DATABASE: PostgreSQL / Supabase
-- =========================================================

BEGIN;

-- =========================================================
-- 0. CREATE SCHEMA
-- =========================================================

CREATE SCHEMA IF NOT EXISTS after_sales;

-- =========================================================
-- 1. RETURN_REQUEST
-- =========================================================

CREATE TABLE IF NOT EXISTS after_sales.return_request (
    return_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    order_id BIGINT NOT NULL,

    customer_id BIGINT,

    return_type VARCHAR(20) NOT NULL,

    return_reason TEXT NOT NULL,

    return_status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',

    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    approved_at TIMESTAMPTZ,

    completed_at TIMESTAMPTZ,

    handled_by INTEGER,

    note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_return_request_order
        FOREIGN KEY (order_id)
        REFERENCES sales.sales_order(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_return_request_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_return_request_staff
        FOREIGN KEY (handled_by)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_return_request_type
        CHECK (
            return_type IN (
                'RETURN',
                'EXCHANGE'
            )
        ),

    CONSTRAINT chk_return_request_status
        CHECK (
            return_status IN (
                'REQUESTED',
                'APPROVED',
                'REJECTED',
                'RETURNING',
                'RECEIVED',
                'COMPLETED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_return_request_approved_at
        CHECK (
            return_status NOT IN (
                'APPROVED',
                'RETURNING',
                'RECEIVED',
                'COMPLETED'
            )
            OR approved_at IS NOT NULL
        ),

    CONSTRAINT chk_return_request_completed_at
        CHECK (
            return_status <> 'COMPLETED'
            OR completed_at IS NOT NULL
        ),

    CONSTRAINT chk_return_request_time_order
        CHECK (
            approved_at IS NULL
            OR requested_at <= approved_at
        ),

    CONSTRAINT chk_return_request_completion_order
        CHECK (
            completed_at IS NULL
            OR requested_at <= completed_at
        )
);

-- =========================================================
-- 2. RETURN_ITEM
-- =========================================================

CREATE TABLE IF NOT EXISTS after_sales.return_item (
    return_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    return_id BIGINT NOT NULL,

    order_item_id BIGINT NOT NULL,

    return_quantity INTEGER NOT NULL,

    return_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    item_condition VARCHAR(50),

    item_reason TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_return_item_request
        FOREIGN KEY (return_id)
        REFERENCES after_sales.return_request(return_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_return_item_order_item
        FOREIGN KEY (order_item_id)
        REFERENCES sales.order_item(order_item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_return_item
        UNIQUE (
            return_id,
            order_item_id
        ),

    CONSTRAINT chk_return_item_quantity
        CHECK (
            return_quantity > 0
        ),

    CONSTRAINT chk_return_item_amount
        CHECK (
            return_amount >= 0
        ),

    CONSTRAINT chk_return_item_condition
        CHECK (
            item_condition IS NULL
            OR item_condition IN (
                'UNOPENED',
                'NEW',
                'USED',
                'DAMAGED',
                'DEFECTIVE',
                'WRONG_ITEM',
                'OTHER'
            )
        )
);

-- =========================================================
-- 3. REFUND
-- =========================================================

CREATE TABLE IF NOT EXISTS after_sales.refund (
    refund_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    payment_id BIGINT NOT NULL,

    return_id BIGINT,

    refund_amount NUMERIC(14,2) NOT NULL,

    refund_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    transaction_code VARCHAR(255),

    reason TEXT,

    refunded_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_refund_payment
        FOREIGN KEY (payment_id)
        REFERENCES sales.payment(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_refund_return_request
        FOREIGN KEY (return_id)
        REFERENCES after_sales.return_request(return_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_refund_transaction_code
        UNIQUE (transaction_code),

    CONSTRAINT chk_refund_amount
        CHECK (
            refund_amount > 0
        ),

    CONSTRAINT chk_refund_status
        CHECK (
            refund_status IN (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_refund_refunded_at
        CHECK (
            refund_status <> 'COMPLETED'
            OR refunded_at IS NOT NULL
        )
);

-- =========================================================
-- 4. REVIEW
-- =========================================================

CREATE TABLE IF NOT EXISTS after_sales.review (
    review_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customer_id BIGINT NOT NULL,

    order_item_id BIGINT NOT NULL,

    rating SMALLINT NOT NULL,

    review_content TEXT,

    review_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_review_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_review_order_item
        FOREIGN KEY (order_item_id)
        REFERENCES sales.order_item(order_item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_review_customer_order_item
        UNIQUE (
            customer_id,
            order_item_id
        ),

    CONSTRAINT chk_review_rating
        CHECK (
            rating BETWEEN 1 AND 5
        ),

    CONSTRAINT chk_review_status
        CHECK (
            review_status IN (
                'PENDING',
                'DISPLAYED',
                'HIDDEN',
                'REJECTED'
            )
        )
);

-- =========================================================
-- 5. REVIEW_MEDIA
-- =========================================================

CREATE TABLE IF NOT EXISTS after_sales.review_media (
    review_id BIGINT NOT NULL,

    media_id BIGINT NOT NULL,

    display_order SMALLINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_review_media
        PRIMARY KEY (
            review_id,
            media_id
        ),

    CONSTRAINT fk_review_media_review
        FOREIGN KEY (review_id)
        REFERENCES after_sales.review(review_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_review_media_media
        FOREIGN KEY (media_id)
        REFERENCES catalog.media(media_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_review_media_display_order
        CHECK (
            display_order >= 0
        )
);

COMMIT;