-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 07_create_customization_measurement_tables.sql
-- PURPOSE:
--   Tạo các bảng:
--   - Yêu cầu may đo
--   - Lịch hẹn đo
--   - Hồ sơ số đo
--   - Chi tiết hồ sơ số đo
--   - Bổ sung FK customization_id cho ORDER_ITEM
-- DATABASE: PostgreSQL / Supabase
-- =========================================================

BEGIN;

-- =========================================================
-- 0. CREATE SCHEMA
-- =========================================================

CREATE SCHEMA IF NOT EXISTS customization;

-- =========================================================
-- 1. CUSTOMIZATION_REQUEST
-- =========================================================

CREATE TABLE IF NOT EXISTS customization.customization_request (
    customization_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customer_id BIGINT NOT NULL,

    product_line_id INTEGER NOT NULL,

    measurement_profile_id BIGINT,

    unit_price NUMERIC(14,2) NOT NULL,

    surcharge_percent NUMERIC(5,2) NOT NULL DEFAULT 0,

    surcharge_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    custom_price NUMERIC(14,2) NOT NULL,

    customization_status VARCHAR(30)
        NOT NULL
        DEFAULT 'REQUESTED',

    customer_note TEXT,

    staff_note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_customization_request_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_customization_request_product_line
        FOREIGN KEY (product_line_id)
        REFERENCES catalog.product_line(product_line_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_customization_unit_price
        CHECK (
            unit_price >= 0
        ),

    CONSTRAINT chk_customization_surcharge_percent
        CHECK (
            surcharge_percent >= 0
            AND surcharge_percent <= 100
        ),

    CONSTRAINT chk_customization_surcharge_amount
        CHECK (
            surcharge_amount >= 0
        ),

    CONSTRAINT chk_customization_custom_price
        CHECK (
            custom_price >= 0
        ),

    CONSTRAINT chk_customization_price_calculation
        CHECK (
            custom_price = unit_price + surcharge_amount
        ),

    CONSTRAINT chk_customization_status
        CHECK (
            customization_status IN (
                'REQUESTED',
                'MEASUREMENT_PENDING',
                'MEASURED',
                'CONFIRMED',
                'IN_PROGRESS',
                'COMPLETED',
                'CANCELLED'
            )
        )
);

-- =========================================================
-- 2. MEASUREMENT_APPOINTMENT
-- =========================================================

CREATE TABLE IF NOT EXISTS customization.measurement_appointment (
    appointment_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customization_id BIGINT NOT NULL,

    customer_id BIGINT NOT NULL,

    branch_id INTEGER NOT NULL,

    staff_id INTEGER,

    appointment_date DATE NOT NULL,

    start_time TIME NOT NULL,

    end_time TIME NOT NULL,

    appointment_status VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',

    customer_note TEXT,

    staff_note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_measurement_appointment_customization
        FOREIGN KEY (customization_id)
        REFERENCES customization.customization_request(customization_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_measurement_appointment_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_measurement_appointment_branch
        FOREIGN KEY (branch_id)
        REFERENCES iam.branch(branch_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_measurement_appointment_staff
        FOREIGN KEY (staff_id)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_measurement_appointment_customization
        UNIQUE (customization_id),

    CONSTRAINT chk_measurement_appointment_time
        CHECK (
            start_time < end_time
        ),

    CONSTRAINT chk_measurement_appointment_duration
        CHECK (
            end_time - start_time <= INTERVAL '4 hours'
        ),

    CONSTRAINT chk_measurement_appointment_status
        CHECK (
            appointment_status IN (
                'PENDING',
                'CONFIRMED',
                'COMPLETED',
                'CANCELLED',
                'NO_SHOW'
            )
        )
);

-- =========================================================
-- 3. MEASUREMENT_PROFILE
-- =========================================================

CREATE TABLE IF NOT EXISTS customization.measurement_profile (
    measurement_profile_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    appointment_id BIGINT,

    customer_id BIGINT NOT NULL,

    measured_by INTEGER,

    profile_type VARCHAR(30) NOT NULL,

    note TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    measurement_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_measurement_profile_appointment
        FOREIGN KEY (appointment_id)
        REFERENCES customization.measurement_appointment(appointment_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_measurement_profile_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_measurement_profile_staff
        FOREIGN KEY (measured_by)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_measurement_profile_type
        CHECK (
            profile_type IN (
                'SIZE_RECOMMENDATION',
                'CUSTOMER_MEASUREMENT'
            )
        ),

    CONSTRAINT chk_measurement_profile_source
        CHECK (
            profile_type <> 'CUSTOMER_MEASUREMENT'
            OR appointment_id IS NOT NULL
        )
);

-- =========================================================
-- 4. ADD FK FROM CUSTOMIZATION_REQUEST TO MEASUREMENT_PROFILE
-- =========================================================
-- CUSTOMIZATION_REQUEST được tạo trước MEASUREMENT_PROFILE,
-- nên khóa ngoại được bổ sung sau khi cả hai bảng đã tồn tại.
-- =========================================================

ALTER TABLE customization.customization_request
    ADD CONSTRAINT fk_customization_request_measurement_profile
    FOREIGN KEY (measurement_profile_id)
    REFERENCES customization.measurement_profile(measurement_profile_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;

-- =========================================================
-- 5. MEASUREMENT_PROFILE_DETAIL
-- =========================================================

CREATE TABLE IF NOT EXISTS customization.measurement_profile_detail (
    measurement_detail_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    measurement_profile_id BIGINT NOT NULL,

    measurement_type_id INTEGER NOT NULL,

    measurement_value NUMERIC(10,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_measurement_profile_detail_profile
        FOREIGN KEY (measurement_profile_id)
        REFERENCES customization.measurement_profile(measurement_profile_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_measurement_profile_detail_type
        FOREIGN KEY (measurement_type_id)
        REFERENCES catalog.measurement_type(measurement_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_measurement_profile_detail
        UNIQUE (
            measurement_profile_id,
            measurement_type_id
        ),

    CONSTRAINT chk_measurement_profile_detail_value
        CHECK (
            measurement_value > 0
        )
);

-- =========================================================
-- 6. ADD CUSTOMIZATION FK TO ORDER_ITEM
-- =========================================================

ALTER TABLE sales.order_item
    ADD CONSTRAINT fk_order_item_customization
    FOREIGN KEY (customization_id)
    REFERENCES customization.customization_request(customization_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT;

COMMIT;