-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 08_create_support_tables.sql
-- PURPOSE:
--   Tạo các bảng:
--   - Cuộc trò chuyện tư vấn
--   - Tin nhắn
--   - Media tin nhắn
--   - Lịch sử phân công nhân viên
--   - Trạng thái đã đọc
--   - Nhãn cuộc trò chuyện
-- DATABASE: PostgreSQL / Supabase
-- =========================================================

BEGIN;

-- =========================================================
-- 0. CREATE SCHEMA
-- =========================================================

CREATE SCHEMA IF NOT EXISTS support;

-- =========================================================
-- 1. CHAT_CONVERSATION
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_conversation (
    conversation_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customer_id BIGINT,

    guest_session_id UUID,

    assigned_staff_id INTEGER,

    channel VARCHAR(20) NOT NULL DEFAULT 'WEB',

    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',

    last_message_at TIMESTAMPTZ,

    closed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_chat_conversation_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_chat_conversation_staff
        FOREIGN KEY (assigned_staff_id)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_chat_conversation_owner
        CHECK (
            (
                customer_id IS NOT NULL
                AND guest_session_id IS NULL
            )
            OR
            (
                customer_id IS NULL
                AND guest_session_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_chat_conversation_channel
        CHECK (
            channel IN (
                'WEB',
                'MOBILE'
            )
        ),

    CONSTRAINT chk_chat_conversation_status
        CHECK (
            status IN (
                'OPEN',
                'WAITING',
                'CLOSED'
            )
        ),

    CONSTRAINT chk_chat_conversation_closed_at
        CHECK (
            status <> 'CLOSED'
            OR closed_at IS NOT NULL
        )
);

-- =========================================================
-- 2. CHAT_MESSAGE
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_message (
    message_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    conversation_id BIGINT NOT NULL,

    sender_type VARCHAR(20) NOT NULL,

    sender_customer_id BIGINT,

    sender_staff_id INTEGER,

    message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT',

    message_content TEXT,

    reply_to_message_id BIGINT,

    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_chat_message_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES support.chat_conversation(conversation_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_message_customer
        FOREIGN KEY (sender_customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_chat_message_staff
        FOREIGN KEY (sender_staff_id)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_chat_message_reply
        FOREIGN KEY (reply_to_message_id)
        REFERENCES support.chat_message(message_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_chat_message_sender_type
        CHECK (
            sender_type IN (
                'CUSTOMER',
                'STAFF',
                'SYSTEM'
            )
        ),

    CONSTRAINT chk_chat_message_sender
        CHECK (
            (
                sender_type = 'CUSTOMER'
                AND sender_customer_id IS NOT NULL
                AND sender_staff_id IS NULL
            )
            OR
            (
                sender_type = 'STAFF'
                AND sender_customer_id IS NULL
                AND sender_staff_id IS NOT NULL
            )
            OR
            (
                sender_type = 'SYSTEM'
                AND sender_customer_id IS NULL
                AND sender_staff_id IS NULL
            )
        ),

    CONSTRAINT chk_chat_message_type
        CHECK (
            message_type IN (
                'TEXT',
                'IMAGE',
                'FILE',
                'SYSTEM'
            )
        ),

    CONSTRAINT chk_chat_message_content
        CHECK (
            message_content IS NOT NULL
            OR message_type IN (
                'IMAGE',
                'FILE'
            )
        )
);

-- =========================================================
-- 3. CHAT_MESSAGE_MEDIA
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_message_media (
    message_id BIGINT NOT NULL,

    media_id BIGINT NOT NULL,

    display_order SMALLINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_chat_message_media
        PRIMARY KEY (
            message_id,
            media_id
        ),

    CONSTRAINT fk_chat_message_media_message
        FOREIGN KEY (message_id)
        REFERENCES support.chat_message(message_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_message_media_media
        FOREIGN KEY (media_id)
        REFERENCES catalog.media(media_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_chat_message_media_display_order
        CHECK (
            display_order >= 0
        )
);

-- =========================================================
-- 4. CHAT_ASSIGNMENT_HISTORY
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_assignment_history (
    assignment_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    conversation_id BIGINT NOT NULL,

    staff_id INTEGER NOT NULL,

    assigned_by INTEGER,

    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    unassigned_at TIMESTAMPTZ,

    reason VARCHAR(255),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_chat_assignment_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES support.chat_conversation(conversation_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_assignment_staff
        FOREIGN KEY (staff_id)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_chat_assignment_assigned_by
        FOREIGN KEY (assigned_by)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_chat_assignment_time
        CHECK (
            unassigned_at IS NULL
            OR assigned_at <= unassigned_at
        )
);

-- =========================================================
-- 5. CHAT_MESSAGE_READ
-- =========================================================
-- reader_id không tạo FK trực tiếp vì có thể tham chiếu
-- customer hoặc staff tùy theo reader_type.
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_message_read (
    message_id BIGINT NOT NULL,

    reader_type VARCHAR(20) NOT NULL,

    reader_id BIGINT NOT NULL,

    read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_chat_message_read
        PRIMARY KEY (
            message_id,
            reader_type,
            reader_id
        ),

    CONSTRAINT fk_chat_message_read_message
        FOREIGN KEY (message_id)
        REFERENCES support.chat_message(message_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_chat_message_reader_type
        CHECK (
            reader_type IN (
                'CUSTOMER',
                'STAFF'
            )
        ),

    CONSTRAINT chk_chat_message_reader_id
        CHECK (
            reader_id > 0
        )
);

-- =========================================================
-- 6. CHAT_TAG
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_tag (
    tag_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    tag_name VARCHAR(100) NOT NULL,

    description VARCHAR(255),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_chat_tag_name
        UNIQUE (tag_name)
);

-- =========================================================
-- 7. CHAT_CONVERSATION_TAG
-- =========================================================

CREATE TABLE IF NOT EXISTS support.chat_conversation_tag (
    conversation_id BIGINT NOT NULL,

    tag_id INTEGER NOT NULL,

    assigned_by INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_chat_conversation_tag
        PRIMARY KEY (
            conversation_id,
            tag_id
        ),

    CONSTRAINT fk_chat_conversation_tag_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES support.chat_conversation(conversation_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_conversation_tag_tag
        FOREIGN KEY (tag_id)
        REFERENCES support.chat_tag(tag_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_chat_conversation_tag_staff
        FOREIGN KEY (assigned_by)
        REFERENCES iam.staff(staff_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

COMMIT;