-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 03_create_catalog_tables.sql
-- PURPOSE:
--   Tạo các bảng danh mục, sản phẩm, size và media
-- DATABASE: PostgreSQL / Supabase
-- =========================================================

BEGIN;

-- =========================================================
-- 0. CREATE SCHEMA
-- =========================================================

CREATE SCHEMA IF NOT EXISTS catalog;

-- =========================================================
-- 1. MEDIA
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.media (
    media_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    media_url TEXT,

    storage_key TEXT NOT NULL,

    alt_text VARCHAR(255),

    media_type VARCHAR(20) NOT NULL,

    mime_type VARCHAR(100),

    file_size BIGINT,

    bucket_name VARCHAR(100) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_media_storage_key
        UNIQUE (storage_key),

    CONSTRAINT chk_media_type
        CHECK (
            media_type IN (
                'IMAGE',
                'VIDEO',
                'FILE'
            )
        ),

    CONSTRAINT chk_media_file_size
        CHECK (
            file_size IS NULL
            OR file_size >= 0
        )
);

-- =========================================================
-- 2. CATEGORY
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.category (
    category_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    category_name VARCHAR(255) NOT NULL,

    description TEXT,

    parent_id INTEGER,

    department VARCHAR(30),

    slug VARCHAR(255) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id)
        REFERENCES catalog.category(category_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT uq_category_slug
        UNIQUE (slug),

    CONSTRAINT chk_category_department
        CHECK (
            department IS NULL
            OR department IN (
                'WOMEN',
                'MEN',
                'KIDS',
                'UNISEX'
            )
        ),

    CONSTRAINT chk_category_not_self_parent
        CHECK (
            parent_id IS NULL
            OR parent_id <> category_id
        )
);

-- =========================================================
-- 3. COLOR
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.color (
    color_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    color_name VARCHAR(100) NOT NULL,

    color_code VARCHAR(7),

    color_group VARCHAR(50),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_color_name
        UNIQUE (color_name),

    CONSTRAINT chk_color_code
        CHECK (
            color_code IS NULL
            OR color_code ~ '^#[0-9A-Fa-f]{6}$'
        )
);

-- =========================================================
-- 4. MATERIAL
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.material (
    material_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    material_name VARCHAR(150) NOT NULL,

    description TEXT,

    care_instruction TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_material_name
        UNIQUE (material_name)
);

-- =========================================================
-- 5. MEASUREMENT_TYPE
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.measurement_type (
    measurement_type_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    measurement_code VARCHAR(50) NOT NULL,

    measurement_name VARCHAR(150) NOT NULL,

    unit VARCHAR(10) NOT NULL DEFAULT 'cm',

    display_order SMALLINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_measurement_type_code
        UNIQUE (measurement_code),

    CONSTRAINT chk_measurement_type_display_order
        CHECK (display_order >= 0)
);

-- =========================================================
-- 6. COLLECTION
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.collection (
    collection_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    collection_name VARCHAR(255) NOT NULL,

    description TEXT,

    media_id BIGINT,

    cultural_story TEXT,

    season VARCHAR(30),

    launch_date DATE,

    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_collection_media
        FOREIGN KEY (media_id)
        REFERENCES catalog.media(media_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_collection_season
        CHECK (
            season IS NULL
            OR season IN (
                'SPRING',
                'SUMMER',
                'AUTUMN',
                'WINTER',
                'TET',
                'HOLIDAY',
                'YEAR_ROUND'
            )
        ),

    CONSTRAINT chk_collection_status
        CHECK (
            status IN (
                'DRAFT',
                'ACTIVE',
                'INACTIVE',
                'ARCHIVED'
            )
        )
);

-- =========================================================
-- 7. PRODUCT_LINE
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.product_line (
    product_line_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    collection_id INTEGER,

    color_id INTEGER,

    material_id INTEGER NOT NULL,

    line_name VARCHAR(255) NOT NULL,

    slug VARCHAR(255) NOT NULL,

    name_meaning VARCHAR(500),

    description TEXT,

    design_style VARCHAR(500),

    features VARCHAR(500),

    usage_context VARCHAR(500),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    is_featured BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_product_line_collection
        FOREIGN KEY (collection_id)
        REFERENCES catalog.collection(collection_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_product_line_color
        FOREIGN KEY (color_id)
        REFERENCES catalog.color(color_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_product_line_material
        FOREIGN KEY (material_id)
        REFERENCES catalog.material(material_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_product_line_slug
        UNIQUE (slug),

    CONSTRAINT chk_product_line_status
        CHECK (
            status IN (
                'DRAFT',
                'ACTIVE',
                'INACTIVE',
                'COMING_SOON',
                'ARCHIVED'
            )
        )
);

-- =========================================================
-- 8. LINE_CATEGORY
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.line_category (
    product_line_id INTEGER NOT NULL,

    category_id INTEGER NOT NULL,

    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT pk_line_category
        PRIMARY KEY (
            product_line_id,
            category_id
        ),

    CONSTRAINT fk_line_category_product_line
        FOREIGN KEY (product_line_id)
        REFERENCES catalog.product_line(product_line_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_line_category_category
        FOREIGN KEY (category_id)
        REFERENCES catalog.category(category_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =========================================================
-- 9. PRODUCT_COMPONENT
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.product_component (
    component_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    product_line_id INTEGER NOT NULL,

    component_name VARCHAR(255) NOT NULL,

    component_type VARCHAR(30) NOT NULL,

    is_required BOOLEAN NOT NULL DEFAULT TRUE,

    display_order SMALLINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_product_component_line
        FOREIGN KEY (product_line_id)
        REFERENCES catalog.product_line(product_line_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_product_component
        UNIQUE (
            product_line_id,
            component_name
        ),

    CONSTRAINT chk_product_component_type
        CHECK (
            component_type IN (
                'SHIRT',
                'PANTS',
                'SKIRT',
                'DRESS',
                'JACKET',
                'ACCESSORY',
                'OTHER'
            )
        ),

    CONSTRAINT chk_product_component_display_order
        CHECK (display_order >= 0)
);

-- =========================================================
-- 10. SIZE_CHART
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.size_chart (
    size_chart_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    chart_name VARCHAR(255) NOT NULL,

    product_line_id INTEGER,

    description TEXT,

    unit VARCHAR(10) NOT NULL DEFAULT 'cm',

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_size_chart_product_line
        FOREIGN KEY (product_line_id)
        REFERENCES catalog.product_line(product_line_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_size_chart_product_line
        UNIQUE (product_line_id)
);

-- =========================================================
-- 11. SIZE_CHART_CATEGORY
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.size_chart_category (
    size_chart_id INTEGER NOT NULL,

    category_id INTEGER NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT pk_size_chart_category
        PRIMARY KEY (
            size_chart_id,
            category_id
        ),

    CONSTRAINT fk_size_chart_category_chart
        FOREIGN KEY (size_chart_id)
        REFERENCES catalog.size_chart(size_chart_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_size_chart_category_category
        FOREIGN KEY (category_id)
        REFERENCES catalog.category(category_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- =========================================================
-- 12. SIZE_OPTION
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.size_option (
    size_option_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    size_chart_id INTEGER NOT NULL,

    size_name VARCHAR(20) NOT NULL,

    display_order SMALLINT NOT NULL DEFAULT 0,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_size_option_chart
        FOREIGN KEY (size_chart_id)
        REFERENCES catalog.size_chart(size_chart_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT uq_size_option
        UNIQUE (
            size_chart_id,
            size_name
        ),

    CONSTRAINT chk_size_option_display_order
        CHECK (display_order >= 0)
);

-- =========================================================
-- 13. SIZE_MEASUREMENT
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.size_measurement (
    measurement_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    size_option_id INTEGER NOT NULL,

    measurement_type_id INTEGER NOT NULL,

    measurement_value NUMERIC(10,2),

    measurement_min NUMERIC(10,2),

    measurement_max NUMERIC(10,2),

    measurement_order SMALLINT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_size_measurement_size_option
        FOREIGN KEY (size_option_id)
        REFERENCES catalog.size_option(size_option_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_size_measurement_type
        FOREIGN KEY (measurement_type_id)
        REFERENCES catalog.measurement_type(measurement_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_size_measurement
        UNIQUE (
            size_option_id,
            measurement_type_id
        ),

    CONSTRAINT chk_size_measurement_value
        CHECK (
            measurement_value IS NULL
            OR measurement_value >= 0
        ),

    CONSTRAINT chk_size_measurement_min
        CHECK (
            measurement_min IS NULL
            OR measurement_min >= 0
        ),

    CONSTRAINT chk_size_measurement_max
        CHECK (
            measurement_max IS NULL
            OR measurement_max >= 0
        ),

    CONSTRAINT chk_size_measurement_range
        CHECK (
            measurement_min IS NULL
            OR measurement_max IS NULL
            OR measurement_min <= measurement_max
        ),

    CONSTRAINT chk_size_measurement_input
        CHECK (
            (
                measurement_value IS NOT NULL
                AND measurement_min IS NULL
                AND measurement_max IS NULL
            )
            OR
            (
                measurement_value IS NULL
                AND measurement_min IS NOT NULL
                AND measurement_max IS NOT NULL
            )
        ),

    CONSTRAINT chk_size_measurement_order
        CHECK (measurement_order >= 0)
);

-- =========================================================
-- 14. PRODUCT_VARIANT
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.product_variant (
    variant_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    sku VARCHAR(100) NOT NULL,

    component_id INTEGER NOT NULL,

    size_option_id INTEGER,

    price NUMERIC(14,2) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_product_variant_sku
        UNIQUE (sku),

    CONSTRAINT fk_product_variant_component
        FOREIGN KEY (component_id)
        REFERENCES catalog.product_component(component_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_product_variant_size
        FOREIGN KEY (size_option_id)
        REFERENCES catalog.size_option(size_option_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_product_variant_price
        CHECK (price >= 0),

    CONSTRAINT chk_product_variant_status
        CHECK (
            status IN (
                'ACTIVE',
                'INACTIVE',
                'COMING_SOON',
                'PREORDER',
                'DISCONTINUED'
            )
        ),

    CONSTRAINT uq_product_variant_component_size
        UNIQUE NULLS NOT DISTINCT (
            component_id,
            size_option_id
        )
);

-- =========================================================
-- 15. PRODUCT_LINE_MEDIA
-- =========================================================

CREATE TABLE IF NOT EXISTS catalog.product_line_media (
    product_line_id INTEGER NOT NULL,

    media_id BIGINT NOT NULL,

    media_role VARCHAR(30) NOT NULL DEFAULT 'GALLERY',

    display_order SMALLINT NOT NULL DEFAULT 0,

    is_primary BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_product_line_media
        PRIMARY KEY (
            product_line_id,
            media_id
        ),

    CONSTRAINT fk_product_line_media_line
        FOREIGN KEY (product_line_id)
        REFERENCES catalog.product_line(product_line_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_product_line_media_media
        FOREIGN KEY (media_id)
        REFERENCES catalog.media(media_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_product_line_media_role
        CHECK (
            media_role IN (
                'MAIN',
                'GALLERY',
                'LOOKBOOK',
                'SIZE_GUIDE',
                'DETAIL'
            )
        ),

    CONSTRAINT chk_product_line_media_display_order
        CHECK (display_order >= 0)
);

COMMIT;