-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 05_create_sales_tables.sql
-- PURPOSE:
--   Tạo các bảng:
--   - Phương thức thanh toán
--   - Giỏ hàng và dòng giỏ hàng
--   - Đơn hàng và dòng đơn hàng
--   - Giao dịch thanh toán
--   - Thông tin giao hàng
-- DATABASE: PostgreSQL / Supabase
-- =========================================================

BEGIN;

-- =========================================================
-- 0. CREATE SCHEMA
-- =========================================================

CREATE SCHEMA IF NOT EXISTS sales;

-- =========================================================
-- 1. PAYMENT_METHOD
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.payment_method (
    method_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    method_name VARCHAR(100) NOT NULL,

    method_code VARCHAR(30) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_payment_method_code
        UNIQUE (method_code),

    CONSTRAINT chk_payment_method_code
        CHECK (
            method_code IN (
                'COD',
                'MOMO',
                'VNPAY',
                'CARD',
                'BANK_TRANSFER'
            )
        )
);

-- =========================================================
-- 2. CART
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.cart (
    cart_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customer_id BIGINT,

    session_id UUID,

    cart_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_cart_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_cart_status
        CHECK (
            cart_status IN (
                'ACTIVE',
                'CHECKED_OUT',
                'ABANDONED',
                'EXPIRED'
            )
        ),

    CONSTRAINT chk_cart_owner
        CHECK (
            (
                customer_id IS NOT NULL
                AND session_id IS NULL
            )
            OR
            (
                customer_id IS NULL
                AND session_id IS NOT NULL
            )
        )
);

-- =========================================================
-- 3. CART_ITEM
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.cart_item (
    cart_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    cart_id BIGINT NOT NULL,

    variant_id INTEGER NOT NULL,

    quantity INTEGER NOT NULL DEFAULT 1,

    unit_price NUMERIC(14,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
        REFERENCES sales.cart(cart_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_cart_item_variant
        FOREIGN KEY (variant_id)
        REFERENCES catalog.product_variant(variant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_cart_item_variant
        UNIQUE (
            cart_id,
            variant_id
        ),

    CONSTRAINT chk_cart_item_quantity
        CHECK (
            quantity > 0
        ),

    CONSTRAINT chk_cart_item_unit_price
        CHECK (
            unit_price >= 0
        )
);

-- =========================================================
-- 4. SALES_ORDER
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.sales_order (
    order_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    order_code VARCHAR(50) NOT NULL,

    customer_id BIGINT,

    order_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    subtotal_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    shipping_fee NUMERIC(14,2) NOT NULL DEFAULT 0,

    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    order_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    customer_note TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT uq_sales_order_code
        UNIQUE (order_code),

    CONSTRAINT fk_sales_order_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_sales_order_subtotal
        CHECK (
            subtotal_amount >= 0
        ),

    CONSTRAINT chk_sales_order_discount
        CHECK (
            discount_amount >= 0
        ),

    CONSTRAINT chk_sales_order_shipping_fee
        CHECK (
            shipping_fee >= 0
        ),

    CONSTRAINT chk_sales_order_total
        CHECK (
            total_amount >= 0
        ),

    CONSTRAINT chk_sales_order_discount_limit
        CHECK (
            discount_amount <= subtotal_amount
        ),

    CONSTRAINT chk_sales_order_total_calculation
        CHECK (
            total_amount =
            subtotal_amount - discount_amount + shipping_fee
        ),

    CONSTRAINT chk_sales_order_status
        CHECK (
            order_status IN (
                'PENDING',
                'CONFIRMED',
                'PACKING',
                'SHIPPING',
                'COMPLETED',
                'CANCELLED',
                'RETURNED'
            )
        ),

    CONSTRAINT chk_sales_order_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'PARTIALLY_PAID',
                'PAID',
                'FAILED',
                'PARTIALLY_REFUNDED',
                'REFUNDED'
            )
        )
);

-- =========================================================
-- 5. ORDER_ITEM
-- =========================================================
-- customization_id chưa tạo FOREIGN KEY tại file này vì
-- bảng customization_request sẽ được tạo ở migration sau.
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.order_item (
    order_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    order_id BIGINT NOT NULL,

    variant_id INTEGER,

    customization_id BIGINT,

    item_type VARCHAR(20) NOT NULL,

    item_name VARCHAR(255) NOT NULL,

    sku VARCHAR(100),

    quantity INTEGER NOT NULL DEFAULT 1,

    unit_price NUMERIC(14,2) NOT NULL,

    discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    line_total NUMERIC(14,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES sales.sales_order(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_order_item_variant
        FOREIGN KEY (variant_id)
        REFERENCES catalog.product_variant(variant_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_order_item_type
        CHECK (
            item_type IN (
                'STANDARD',
                'CUSTOMIZED'
            )
        ),

    CONSTRAINT chk_order_item_reference
        CHECK (
            (
                item_type = 'STANDARD'
                AND variant_id IS NOT NULL
                AND customization_id IS NULL
            )
            OR
            (
                item_type = 'CUSTOMIZED'
                AND variant_id IS NULL
                AND customization_id IS NOT NULL
            )
        ),

    CONSTRAINT chk_order_item_quantity
        CHECK (
            quantity > 0
        ),

    CONSTRAINT chk_order_item_unit_price
        CHECK (
            unit_price >= 0
        ),

    CONSTRAINT chk_order_item_discount
        CHECK (
            discount_amount >= 0
        ),

    CONSTRAINT chk_order_item_discount_limit
        CHECK (
            discount_amount <= unit_price * quantity
        ),

    CONSTRAINT chk_order_item_line_total
        CHECK (
            line_total =
            unit_price * quantity - discount_amount
        )
);

-- =========================================================
-- 6. PAYMENT
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.payment (
    payment_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    order_id BIGINT NOT NULL,

    method_id INTEGER NOT NULL,

    amount NUMERIC(14,2) NOT NULL,

    payment_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    transaction_code VARCHAR(255),

    paid_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
        REFERENCES sales.sales_order(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_payment_method
        FOREIGN KEY (method_id)
        REFERENCES sales.payment_method(method_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_payment_transaction_code
        UNIQUE (transaction_code),

    CONSTRAINT chk_payment_amount
        CHECK (
            amount > 0
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'PROCESSING',
                'PAID',
                'FAILED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_payment_paid_at
        CHECK (
            payment_status <> 'PAID'
            OR paid_at IS NOT NULL
        )
);

-- =========================================================
-- 7. SHIPPING
-- =========================================================

CREATE TABLE IF NOT EXISTS sales.shipping (
    shipping_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    order_id BIGINT NOT NULL,

    address_id BIGINT NOT NULL,

    shipping_provider VARCHAR(100),

    tracking_code VARCHAR(100),

    shipping_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    shipped_at TIMESTAMPTZ,

    delivered_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ,

    CONSTRAINT fk_shipping_order
        FOREIGN KEY (order_id)
        REFERENCES sales.sales_order(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_shipping_address
        FOREIGN KEY (address_id)
        REFERENCES iam.address(address_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_shipping_tracking_code
        UNIQUE (tracking_code),

    CONSTRAINT chk_shipping_status
        CHECK (
            shipping_status IN (
                'PENDING',
                'CONFIRMED',
                'PICKED_UP',
                'IN_TRANSIT',
                'DELIVERED',
                'FAILED',
                'RETURNING',
                'RETURNED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_shipping_shipped_at
        CHECK (
            shipping_status NOT IN (
                'PICKED_UP',
                'IN_TRANSIT',
                'DELIVERED',
                'FAILED',
                'RETURNING',
                'RETURNED'
            )
            OR shipped_at IS NOT NULL
        ),

    CONSTRAINT chk_shipping_delivered_at
        CHECK (
            shipping_status <> 'DELIVERED'
            OR delivered_at IS NOT NULL
        ),

    CONSTRAINT chk_shipping_time_order
        CHECK (
            shipped_at IS NULL
            OR delivered_at IS NULL
            OR shipped_at <= delivered_at
        )
);

COMMIT;