-- =========================================================
-- PROJECT: XEOXO WEB
-- FILE: 02_create_iam_tables.sql
-- PURPOSE:
--   Tạo các bảng tài khoản nghiệp vụ, khách hàng,
--   nhân viên, chi nhánh và địa chỉ.
--
-- AUTHENTICATION:
--   Sử dụng Supabase Auth.
--   Email, phone, password, OTP và OAuth provider
--   được quản lý bởi schema auth.
-- =========================================================

BEGIN;


-- =========================================================
-- 1. ACCOUNT
-- Hồ sơ nghiệp vụ mở rộng của auth.users
-- =========================================================
CREATE TABLE IF NOT EXISTS iam.account (
    account_id UUID PRIMARY KEY,

    role VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER'
        CONSTRAINT ck_account_role
        CHECK (
            role IN (
                'CUSTOMER',
                'STAFF',
                'ADMIN'
            )
        ),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_account_auth_user
        FOREIGN KEY (account_id)
        REFERENCES auth.users(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

COMMENT ON TABLE iam.account IS
'Hồ sơ tài khoản nghiệp vụ mở rộng từ Supabase Auth.';

COMMENT ON COLUMN iam.account.account_id IS
'Khóa chính đồng thời tham chiếu auth.users.id.';

COMMENT ON COLUMN iam.account.role IS
'Vai trò nghiệp vụ của tài khoản: CUSTOMER, STAFF hoặc ADMIN.';

COMMENT ON COLUMN iam.account.is_active IS
'Cho biết tài khoản có được phép hoạt động trong hệ thống hay không.';


-- =========================================================
-- 2. CUSTOMER
-- Hồ sơ khách hàng
-- =========================================================
CREATE TABLE IF NOT EXISTS iam.customer (
    customer_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    account_id UUID,

    customer_name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(20),

    customer_type VARCHAR(20) NOT NULL DEFAULT 'REGULAR'
        CONSTRAINT ck_customer_type
        CHECK (
            customer_type IN (
                'REGULAR',
                'MEMBER',
                'VIP'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_customer_account
        UNIQUE (account_id),

    CONSTRAINT fk_customer_account
        FOREIGN KEY (account_id)
        REFERENCES iam.account(account_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

COMMENT ON TABLE iam.customer IS
'Lưu hồ sơ nghiệp vụ của khách hàng.';

COMMENT ON COLUMN iam.customer.account_id IS
'Tài khoản đăng nhập liên kết với khách hàng; NULL đối với khách chưa có tài khoản.';

COMMENT ON COLUMN iam.customer.email IS
'Email liên hệ nghiệp vụ, không phải email đăng nhập.';

COMMENT ON COLUMN iam.customer.phone IS
'Số điện thoại liên hệ nghiệp vụ, không phải số điện thoại đăng nhập.';

COMMENT ON COLUMN iam.customer.customer_type IS
'Phân loại khách hàng: REGULAR, MEMBER hoặc VIP.';


-- =========================================================
-- 3. PROVINCE
-- Danh mục tỉnh/thành phố Việt Nam
-- =========================================================
CREATE TABLE IF NOT EXISTS iam.province (
    province_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    province_name VARCHAR(150) NOT NULL,

    region VARCHAR(20)
        CONSTRAINT ck_province_region
        CHECK (
            region IS NULL
            OR region IN (
                'NORTH',
                'CENTRAL',
                'SOUTH'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_province_name
        UNIQUE (province_name)
);

COMMENT ON TABLE iam.province IS
'Danh mục tỉnh và thành phố của Việt Nam.';

COMMENT ON COLUMN iam.province.region IS
'Vùng địa lý: NORTH, CENTRAL hoặc SOUTH.';


-- =========================================================
-- 4. BRANCH
-- Tạo trước STAFF.
-- manager_id chưa gắn FK ngay vì BRANCH và STAFF
-- tham chiếu vòng lẫn nhau.
-- =========================================================
CREATE TABLE IF NOT EXISTS iam.branch (
    branch_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    branch_name VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    phone VARCHAR(20),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    manager_id INTEGER,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_branch_name
        UNIQUE (branch_name)
);

COMMENT ON TABLE iam.branch IS
'Lưu thông tin các chi nhánh của hệ thống.';

COMMENT ON COLUMN iam.branch.manager_id IS
'Nhân viên đang được chỉ định làm quản lý chi nhánh.';


-- =========================================================
-- 5. STAFF
-- Hồ sơ nhân viên
-- =========================================================
CREATE TABLE IF NOT EXISTS iam.staff (
    staff_id INTEGER
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    account_id UUID NOT NULL,
    branch_id INTEGER NOT NULL,

    staff_name VARCHAR(255) NOT NULL,
    position VARCHAR(100) NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_staff_account
        UNIQUE (account_id),

    CONSTRAINT fk_staff_account
        FOREIGN KEY (account_id)
        REFERENCES iam.account(account_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_staff_branch
        FOREIGN KEY (branch_id)
        REFERENCES iam.branch(branch_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE iam.staff IS
'Lưu hồ sơ nghiệp vụ của nhân viên.';

COMMENT ON COLUMN iam.staff.account_id IS
'Tài khoản Supabase Auth được liên kết thông qua iam.account.';

COMMENT ON COLUMN iam.staff.branch_id IS
'Chi nhánh mà nhân viên đang làm việc.';


-- =========================================================
-- 6. THÊM FK MANAGER CHO BRANCH
-- Thực hiện sau khi bảng STAFF đã tồn tại.
-- =========================================================
ALTER TABLE iam.branch
    ADD CONSTRAINT fk_branch_manager
    FOREIGN KEY (manager_id)
    REFERENCES iam.staff(staff_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL;


-- =========================================================
-- 7. ADDRESS
-- Địa chỉ nhận hàng của khách hàng
-- =========================================================
CREATE TABLE IF NOT EXISTS iam.address (
    address_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    customer_id BIGINT NOT NULL,

    recipient_name VARCHAR(255) NOT NULL,
    recipient_phone VARCHAR(20) NOT NULL,

    province_id INTEGER NOT NULL,
    district_name VARCHAR(150) NOT NULL,
    address_detail TEXT NOT NULL,

    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_address_customer
        FOREIGN KEY (customer_id)
        REFERENCES iam.customer(customer_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_address_province
        FOREIGN KEY (province_id)
        REFERENCES iam.province(province_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

COMMENT ON TABLE iam.address IS
'Lưu các địa chỉ nhận hàng của khách hàng.';

COMMENT ON COLUMN iam.address.is_default IS
'Cho biết đây có phải địa chỉ mặc định của khách hàng hay không.';

COMMENT ON COLUMN iam.address.is_active IS
'Cho biết địa chỉ còn được khách hàng sử dụng hay không.';


COMMIT;